### ISSUE TITLE
CocoaPods Issue

### ISSUE THREAD

**Issue by norfred** [jverdi/Gramophone#1] opened 2017-04-11 20:52 UTC
Integrating with Cocoapods throws an error:

> _[!] Unable to find a specification for `Gramophone (~> 1.0)`_

**Comment by jverdi** [comment] 2017-04-11 21:35
@norfred hmm.. it seems to be working for me in a brand new project. Could you share the relevant part of your Podfile?

**Comment by norfred** [comment] 2017-04-12 12:20
Sure, here it is:
```
platform :ios, '10.0'
use_frameworks!

target 'App' do
    pod 'Gramophone'
end
```
I've also noticed that [specs link](https://github.com/CocoaPods/Specs/tree/master/Specs/Gramophone/1.0/Gramophone.podspec.json) for Gramophone is unavailable!

**Comment by jverdi** [comment] 2017-04-13 01:09
I noticed the specs link issue too. Not sure what's going on there, but it does exist in the repo: https://github.com/CocoaPods/Specs/blob/master/Specs/5/d/9/Gramophone/1.0/Gramophone.podspec.json

I'm unfortunately not able to reproduce the issue integrating though. Can you add the line `source 'https://github.com/CocoaPods/Specs.git'` to the top of your Podfile, just to be sure?

I'm also noticing a strange issue with the cocoadocs import: http://api.cocoadocs.org:4567/error/Gramophone/1.0

**Comment by jverdi** [comment] 2017-10-14 18:00
I know it has been a while, but I just made a new release, version 1.1. 

It seems like the specs linkage through the API is working better for this release:
https://trunk.cocoapods.org/api/v1/pods/Gramophone/specs/latest

I'm going to close this issue now, but feel free to re-open if issues remain.

**Closed as completed by jverdi** 2017-10-14 18:00 UTC
